[package]
name = "decto"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.x", features = ["derive"] }
itertools = "0.14.x"
fraction = { version = "0.15.x", features = ["with-bigint"] }
# bigdecimal = "0.4.x"